using UnityEngine;
using System;
using System.Collections.Generic;

// *** Class Generated By SaveDataEditor ***
namespace CarterGames.Assets.SaveManager
{
    [Serializable]
    public class SaveData
    {
        public int levelNumber = 1;
        public int pieceNumber = 0;
        public float levelTravelled = 0f;

        public bool continueGame = false;
    }
}
